package model;
// Generated Dec 8, 2019 2:11:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="Orders"
    ,schema="dbo"
    ,catalog="Java_WebBanDoDien"
)
public class Orders  implements java.io.Serializable {


     private int id;
     private Users users;
     private Date orderDate;
     private Double shipmentPrice;
     private Date receiveDate;
     private Set<OrderItems> orderItemses = new HashSet<OrderItems>(0);

    public Orders() {
    }

	
    public Orders(int id) {
        this.id = id;
    }
    public Orders(int id, Users users, Date orderDate, Double shipmentPrice, Date receiveDate, Set<OrderItems> orderItemses) {
       this.id = id;
       this.users = users;
       this.orderDate = orderDate;
       this.shipmentPrice = shipmentPrice;
       this.receiveDate = receiveDate;
       this.orderItemses = orderItemses;
    }
   
    @Id @GeneratedValue


    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UserId")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OrderDate", length=23)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="ShipmentPrice", precision=18, scale=0)
    public Double getShipmentPrice() {
        return this.shipmentPrice;
    }
    
    public void setShipmentPrice(Double shipmentPrice) {
        this.shipmentPrice = shipmentPrice;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ReceiveDate", length=23)
    public Date getReceiveDate() {
        return this.receiveDate;
    }
    
    public void setReceiveDate(Date receiveDate) {
        this.receiveDate = receiveDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set<OrderItems> getOrderItemses() {
        return this.orderItemses;
    }
    
    public void setOrderItemses(Set<OrderItems> orderItemses) {
        this.orderItemses = orderItemses;
    }




}


