package model;
// Generated Jan 4, 2020 3:58:57 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="Users"
    ,schema="dbo"
    ,catalog="Java_WebBanDoDien"
)
public class Users  implements java.io.Serializable {


     private int id;
     private String userName;
     private String password;
     private Date createdAt;
     private Integer role;
     private String address;
     private String phone;
     private String email;

    public Users() {
    }

	
    public Users(int id) {
        this.id = id;
    }
    public Users(int id, String userName, String password, Date createdAt, Integer role, String address, String phone, String email) {
       this.id = id;
       this.userName = userName;
       this.password = password;
       this.createdAt = createdAt;
       this.role = role;
       this.address = address;
       this.phone = phone;
       this.email = email;
    }
   
    @Id @GeneratedValue

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="UserName")
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="Password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedAt", length=23)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    
    @Column(name="Role")
    public Integer getRole() {
        return this.role;
    }
    
    public void setRole(Integer role) {
        this.role = role;
    }

    
    @Column(name="Address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="Phone")
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="Email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


